version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bancoPOO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - app-network

  web:
    build: .
    command: gunicorn roboleran.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
