# Generated by Django 5.1.2 on 2024-11-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/')),
                ('nome', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.asset')),
            ],
        ),
    ]
