# Generated by Django 5.1.2 on 2024-11-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_jogo_assets_jogo_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='assets',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
