# Generated by Django 5.1.2 on 2024-11-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_jogo_assets_delete_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='diretorio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
